services:
  app:
    container_name: node-container
    build:  
      context: .
    volumes:
      - ./src:/usr/src/app/src
    working_dir: /usr/src/app/src
    command: npm run dev
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src/infra:/docker-entrypoint-initdb.d
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
